<?php

require_once ('phpsysinfo/init.inc.php');
require_once ('check_sys.inc');

/**
 * Implements hook_init().
 */
function system_monitor_init()
{
	drupal_add_js('https://www.google.com/jsapi', 'external');
}

/**
 * Implement hook_help().
 */
function system_monitor_help($path, $arg)
{
	if ($path == 'admin/help#system_monitor') {
		return t('<em>System Activity Monitor</em> Monitor system activity in real time.');
	}
}

/*
 ** implement hook_theme()
 function system_monitor_theme()
 {
 }
 */

/*
 * Implement hook_block()
 */

/**
 * Implements hook_menu().
 *
 * Provides a default page to explain what this module does.
 */
function system_monitor_menu()
{
	// for admin
	$items['admin/config/system/system_monitor'] = array(
		'title' => 'Configure System Monitor Module',
		'description' => 'Configure parameters of System Monitor Module',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('system_monitor_admin_config'),
		'access arguments' => array('administer users'),
		'type' => MENU_NORMAL_ITEM,
		'file' => 'system_monitor.admin.inc',
	);

	$items['system_monitor'] = array(
		'page callback' => 'system_monitor_page',
		'access callback' => TRUE,
		'title' => 'System Activity Monitor',
	);

	// ajax handler
	$items['ajax/mon/%'] = array(
		'title' => 'AJAX handler for monitoring',
		'page callback' => 'ajax_mon_handler',
		'page arguments' => array(2),
		'access arguments' => array('access content'),
		'type' => MENU_CALLBACK,
	);

	return $items;
}

/**
 * Simple page function to explain what the block example is about.
 */
function system_monitor_page()
{
	if (!defined('PSI_CONFIG_FILE') || !defined('PSI_DEBUG')) {
		dpm('error');
		return;
		/*
		$tpl = new Template("/templates/html/error_config.html");
		echo $tpl->fetch();
		die();
		 */
	}

	// redirect to page with and without javascript
	$html = null;
	$display = isset($_GET['disp']) ? $_GET['disp'] : strtolower(PSI_DEFAULT_DISPLAY_MODE);
	switch ($display) {
		case "static" :
			$webpage = new WebpageXSLT();
			$html = $webpage->run();
			break;
		case "dynamic" :
			$webpage = new Webpage();
			$html = $webpage->run();
			break;
		case "xml" :
			$webpage = new WebpageXML(true, null);
			$html = $webpage->run();
			break;
		default :
			$tpl = new Template("/templates/html/index_all.html");
			$html = $tpl->fetch();
			break;
	}

	dpm($html);
	$page = array(
		'#type' => 'markup',
		'#markup' => $html,
	);
	return $page;
}

/**
 * Implements hook_block_info().
 *
 * This hook declares what blocks are provided by the module.
 */
function system_monitor_block_info()
{
	$blocks['system_monitor_cpu_load'] = array(
		'info' => t('Monitor CPU Usage'),
		'status' => TRUE,
		'region' => 'sidebar_first',
	);
	$blocks['system_monitor_cpu_loadavg'] = array(
		'info' => t('Monitor CPU Load Average'),
		'status' => TRUE,
		'region' => 'sidebar_first',
	);
	return $blocks;
}

/**
 * Implements hook_block_view().
 *
 * This hook generates the contents of the blocks themselves.
 */
function system_monitor_block_view($delta = '')
{
	drupal_add_js(drupal_get_path('module', 'system_monitor') . 'js/system_monitor.js');

	// The $delta parameter tells us which block is being requested.
	$block = array();
	switch ($delta) {
		case 'system_monitor_cpu_load' :
			$interval = variable_get('cpu_interval', array());
			$w = variable_get('cpu_chart_width');
			$h = variable_get('cpu_chart_height');
			$block['subject'] = t("CPU Usage ");
			$block['content'] = "<div id='system_monitor_cpu_load' interval='$interval' width='$w' height='$h'></div>";
			break;
		case 'system_monitor_cpu_loadavg':
			$interval = variable_get('cpu_interval', array());
			$w = variable_get('cpu_chart_width');
			$h = variable_get('cpu_chart_height');
			$block['subject'] = t("CPU Load Average ");
			$block['content'] = "<div id='system_monitor_cpu_loadavg' interval='$interval' width='$w' height='$h'></div>";
			break;
	}
	return $block;
}
